version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}?schema=public
      MAILER_USER: ${MAILER_USER}
      MAILER_PASS: ${MAILER_PASS}
      MAILER_SENDER: ${MAILER_SENDER}
      MAILER_HOST: ${MAILER_HOST}
      ENCRYPT_SALT: ${ENCRYPT_SALT}
    ports:
      - "${API_PORT}:3000"
    volumes:
      - /uploads
    depends_on:
      - db
      
volumes:
  db_data: